# Generated by Django 4.2 on 2023-06-27 18:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Empleado')),
                ('nombreEmpleado', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idenvio', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Envio')),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.CharField(choices=[('Dimensionado', 'Dimensionado'), ('Forro', 'Forro'), ('Traslapo', 'Traslapo'), ('Molduras', 'Molduras')], default='Dimensionado')),
                ('dimensionado', models.CharField(default='2x3', max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutC', models.CharField(max_length=12, verbose_name='Rut Cliente')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellidoPaterno', models.CharField(max_length=45, verbose_name='Apellido')),
                ('correo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fechaIngreso', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('estadopedido', models.CharField(choices=[('Activo', 'En curso'), ('Entregado', 'Finalizado')], default='Activo', max_length=30)),
                ('reparto', models.CharField(choices=[('Envío', 'Envío'), ('Sin Envío', 'Sin Envío')], default='Sin Envío', max_length=30)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
                ('productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Historial Pedidos')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.pedido')),
            ],
        ),
    ]
