# Generated by Django 4.2.2 on 2023-06-08 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Empleado')),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idEnvio', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Envio')),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idPedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('estadoP', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Producto')),
                ('tipo', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('valor', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutC', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idHistorial', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Historial Pedidos')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.pedido')),
            ],
            options={
                'verbose_name': 'Historial',
                'verbose_name_plural': 'Historiales',
            },
        ),
    ]
