# Generated by Django 4.2.1 on 2023-06-13 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Empleado')),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('idenvio', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Codigo Envio')),
                ('direccion', models.CharField(max_length=50)),
                ('estado', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('categoria', models.IntegerField(choices=[(1, 'Dimensionado'), (2, 'Forro'), (3, 'Traslapo'), (4, 'Molduras')], default=1)),
                ('dimensionado', models.CharField(default='2x3', max_length=45)),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rutC', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('apellidoPaterno', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=50)),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('idpedido', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('estadoP', models.CharField(max_length=50)),
                ('fechaIngreso', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=255)),
                ('precio', models.IntegerField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.usuario')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.envio')),
                ('productos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.BigIntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='Historial Pedidos')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.pedido')),
            ],
        ),
    ]
